// Generated by CoffeeScript 1.12.4
var defaultAssert, defaults, registry;

defaults = require("./defaults");

registry = Object.create(null);

exports.get = function(id) {
  var validator;
  if (validator = registry[id]) {
    return validator;
  }
  throw Error("Unknown type: '" + id + "'");
};

exports.set = function(id, validator) {
  if (typeof validator.assert !== "function") {
    validator.assert = defaultAssert;
  }
  registry[id] = validator;
};

defaultAssert = function(value) {
  if (!this.test(value)) {
    return this.error;
  }
};

Object.keys(defaults).forEach(function(id) {
  return exports.set(id, defaults[id]);
});
