// Generated by CoffeeScript 1.12.4
var registry;

registry = Object.create(null);

exports.get = function(tag) {
  var validator;
  if (validator = registry[tag]) {
    return validator;
  }
  throw Error("Unknown type: '" + tag + "'");
};

exports.set = function(tag, validator) {
  registry[tag] = validator;
  return validator;
};
