// Generated by CoffeeScript 1.12.4
var addons, defaultAssert, isObject, isValidator, testAssert, valido, validoTag, wrapAssert;

isObject = require("isObject");

wrapAssert = require("./utils/wrapAssert");

validoTag = "valido_" + Math.random().toString(16).slice(2, 6);

addons = [];

addons.isValido = function(value) {
  return value[validoTag] === true;
};

valido = function(config) {
  var name;
  if (arguments.length > 1) {
    name = config;
    config = arguments[1];
  }
  if (Array.isArray(config)) {
    return addons.Either(config);
  }
  if (typeof config === "function") {
    config = {
      assert: config
    };
  } else if (isObject(config)) {
    if (!isValidator(config)) {
      return addons.Shape(config);
    }
  } else {
    throw TypeError("Expected an object, function, or array");
  }
  if (typeof config.assert !== "function") {
    config.assert = defaultAssert;
  } else if (typeof config.test !== "function") {
    config.test = testAssert;
  }
  config.assert = wrapAssert(config.assert);
  Object.defineProperty(config, validoTag, {
    value: true
  });
  if (name) {
    config.name = name;
  }
  return config;
};

valido.add = function(addon, resolve) {
  addons.push(valido(addon));
  addon.resolve = resolve;
  return addon;
};

Object.defineProperty(valido, "_addons", {
  value: addons
});

module.exports = valido;

testAssert = function(value) {
  return this.assert(value) === void 0;
};

defaultAssert = function(value) {
  if (!this.test(value)) {
    return this.error;
  }
};

isValidator = function(config) {
  if (typeof config.assert === "function") {
    return true;
  }
  if (typeof config.test === "function") {
    if (typeof config.error === "function") {
      return true;
    }
    if (typeof config.assert === "function") {
      return true;
    }
    throw Error("Validators must have an `assert` or `error` function");
  }
  return false;
};
