// Generated by CoffeeScript 1.12.4
var addons, identifyType, isObject, reducer, valido;

isObject = require("isObject");

valido = require("../valido");

addons = valido._addons;

identifyType = function(type) {
  if (typeof type === "string") {
    return type;
  }
  if (!(isObject(type) && !addons.isValido(type))) {
    if (typeof type.name === "string") {
      return type.name;
    }
  }
};

reducer = function(array, type) {
  var name;
  if (name = identifyType(type)) {
    array.push(name);
  }
  return array;
};

module.exports = function(type) {
  if (Array.isArray(type)) {
    return type.reduce(reducer, []);
  } else {
    return identifyType(type);
  }
};
