// Generated by CoffeeScript 1.12.4
var identifyType, isObject, resolveError, wrongType;

isObject = require("isObject");

identifyType = require("./identifyType");

wrongType = require("./wrongType");

resolveError = function(key, type) {
  if (typeof type === "string") {
    if (type[type.length - 1] === "?") {
      type = type.slice(0, -1);
    }
    if (type.indexOf("|") !== -1) {
      type = type.split("|");
    }
    return wrongType(key, type);
  } else if (Array.isArray(type)) {
    return wrongType(key, identifyType(type));
  } else if (isObject(type)) {
    return wrongType(key, "object");
  } else {
    return TypeError("`" + key + "` is an invalid type");
  }
};

module.exports = resolveError;
