// Generated by CoffeeScript 1.12.4
var addons, registry, resolveAddon, resolveTag, resolveType, valido;

registry = require("../registry");

valido = require("../valido");

addons = valido._addons;

resolveType = function(value) {
  if (typeof value === "string") {
    return resolveTag(value);
  }
  if (addons.isValido(value)) {
    return value;
  }
  return resolveAddon(value);
};

module.exports = resolveType;

resolveTag = function(tag) {
  if (tag[tag.length - 1] === "?") {
    return addons.Maybe(tag.slice(0, -1));
  }
  if (tag.indexOf("|") !== -1) {
    return addons.Either(tag.split("|"));
  }
  return registry.get(tag);
};

resolveAddon = function(value) {
  var addon, i, len, validator;
  for (i = 0, len = addons.length; i < len; i++) {
    addon = addons[i];
    if (addon.resolve(value)) {
      validator = Object.create(addon);
      if (typeof validator.init === "function") {
        validator.init(value);
      }
      return validator;
    }
  }
  throw Error("Unsupported validator");
};
