// Generated by CoffeeScript 1.12.4
var bindError, formatPath, keys, wrapAssert;

keys = [];

wrapAssert = function(assert) {
  return function(value, key) {
    var error;
    if (error = assert.call(this, value)) {
      if (key) {
        keys.unshift(key);
      } else if (keys.length === 0) {
        return error;
      }
      return bindError(error);
    }
  };
};

module.exports = wrapAssert;

bindError = function(createError) {
  var bound, path;
  path = keys;
  keys = [];
  bound = function(key) {
    return createError(formatPath(key, path));
  };
  bound.path = path;
  return bound;
};

formatPath = function(key, path) {
  if (key) {
    path.unshift(key);
  } else if (path.length === 0) {
    return null;
  }
  return path.join(".");
};
