// Generated by CoffeeScript 1.12.4
var expected, validator, wrongType;

wrongType = require("../wrongType");

expected = null;

validator = {};

validator.test = function(value) {
  var valid;
  valid = (value != null) && value.constructor === expected;
  expected = null;
  return valid;
};

validator.assert = function(value) {
  var name;
  if ((value != null) && value.constructor === expected) {
    expected = null;
    return;
  }
  name = expected.name;
  expected = null;
  return function(key) {
    return wrongType(key, name);
  };
};

module.exports = function(type) {
  expected = type;
  return validator;
};
