// Generated by CoffeeScript 1.12.4
var Either, expected, getValidator, registry, validator;

registry = require("../registry");

Either = require("./Either");

expected = null;

validator = {};

validator.test = function(value) {
  var valid;
  valid = value === void 0 || getValidator().test(value);
  expected = null;
  return valid;
};

validator.assert = function(value) {
  var error;
  if (value === void 0) {
    expected = null;
    return;
  }
  error = getValidator().assert(value);
  expected = null;
  return error;
};

getValidator = function() {
  if (0 <= expected.indexOf("|")) {
    return Either(expected.split("|"));
  }
  return registry.get(expected);
};

module.exports = function(type) {
  expected = type;
  return validator;
};
