// Generated by CoffeeScript 1.12.4
var assertConstructor, testConstructor, validator, valido, wrongType;

wrongType = require("../utils/wrongType");

valido = require("../valido");

testConstructor = function(value) {
  return (value != null) && value.constructor === this.type;
};

assertConstructor = function(value) {
  if ((value == null) || value.constructor !== this.type) {
    return this.error.bind(this);
  }
};

validator = {
  test: testConstructor,
  assert: assertConstructor
};

validator.init = function(type) {
  this.name = type.name;
  this.type = type;
};

validator.error = function(key) {
  return wrongType(key, this.name);
};

valido.add(validator, function(value) {
  return typeof value === "function";
});
