// Generated by CoffeeScript 1.12.4
var addons, assertEither, identifyType, resolveType, testEither, validator, valido, wrongType;

identifyType = require("../utils/identifyType");

resolveType = require("../utils/resolveType");

wrongType = require("../utils/wrongType");

valido = require("../valido");

addons = valido._addons;

testEither = function(value) {
  var i, len, ref, type;
  if (value === void 0) {
    return this.optional;
  }
  if (value === null) {
    return this.nullable;
  }
  ref = this.types;
  for (i = 0, len = ref.length; i < len; i++) {
    type = ref[i];
    if (type.test(value)) {
      return true;
    }
  }
  return false;
};

assertEither = function(value) {
  var error, i, len, ref, type;
  if (this.optional && value === void 0) {
    return;
  }
  if (this.nullable && value === null) {
    return;
  }
  ref = this.types;
  for (i = 0, len = ref.length; i < len; i++) {
    type = ref[i];
    if (!(error = type.assert(value))) {
      return;
    }
    if (error.path) {
      return error;
    }
  }
  return this.error.bind(this);
};

validator = {
  test: testEither,
  assert: assertEither
};

validator.init = function(types) {
  if (!Array.isArray(types)) {
    throw TypeError("Expected an array");
  }
  if (this.optional = types[types.length - 1] === "?") {
    types = types.slice(0, -1);
  }
  if (this.nullable = types[types.length - 1] === "null") {
    types = types.slice(0, -1);
  }
  this.types = types.map(resolveType);
};

validator.error = function(key) {
  var names;
  names = identifyType(this.types);
  if (this.nullable) {
    names.push("null");
  }
  return wrongType(key, names);
};

valido.add(validator, Array.isArray);

addons.Either = function(types) {
  var inst;
  inst = Object.create(validator);
  inst.init(types);
  return inst;
};
