// Generated by CoffeeScript 1.12.4
var addons, assertMaybe, registry, testMaybe, validator, valido;

registry = require("../registry");

valido = require("../valido");

addons = valido._addons;

testMaybe = function(value) {
  if (value === void 0) {
    return true;
  }
  return this.type.test(value);
};

assertMaybe = function(value) {
  if (value !== void 0) {
    return this.type.assert(value);
  }
};

validator = valido({
  test: testMaybe,
  assert: assertMaybe
});

validator.init = function(type) {
  this.type = type.indexOf("|") !== -1 ? addons.Either(type.split("|")) : registry.get(type);
};

Object.defineProperty(validator, "name", {
  get: function() {
    return this.type.name;
  },
  set: function() {
    throw Error("`name` is not writable");
  }
});

addons.Maybe = function(type) {
  var inst;
  inst = Object.create(validator);
  inst.init(type);
  return inst;
};
