// Generated by CoffeeScript 1.12.4
var addons, assertMaybe, registry, validateMaybe, validator, valido;

registry = require("../registry");

valido = require("../valido");

addons = valido._addons;

validateMaybe = function(value) {
  if (value === void 0) {
    return true;
  }
  return this.type.validate(value);
};

assertMaybe = function(value) {
  if (value !== void 0) {
    return this.type.assert(value);
  }
};

validator = valido({
  validate: validateMaybe,
  assert: assertMaybe
});

validator.init = function(type) {
  this.type = type.indexOf("|") !== -1 ? addons.Either(type.split("|")) : registry.get(type);
};

addons.Maybe = function(type) {
  var inst;
  inst = Object.create(validator);
  inst.init(type);
  return inst;
};
